### PR TITLE
IMaterialControl has to be public for NuGet, Csharp 6 and Net 4.6.1 Updates, Code Tidy Up

### PR DESCRIPTION
**Pull request by michalkrzych**
Major:
- Updated .NET Framework version to 4.6.1
- Changed access modifier from default(internal) to public in
  IMaterialControl - when released as a NuGet package this will now allow
  developers to implement IMaterialControl and therefore create their own
  custom Material based controls.

Minor:
- Converted some property getters to expressions (C# 6.0 feature)
- Renamed private fields to start with an underscore (Naming
  Conventions)
- Added null propagation for event raises
- Updated Assembly versions for the MaterialSkin library and for the
  example app
- Removed unused references

### CODE REVIEW

**Comment by michalkrzych** [comment]
It would be _fantastic_ if this was merged to the original repo @ https://github.com/IgnaceMaes/MaterialSkin and released as a NuGet package to allow people to actually implement custom User Controls implementing **_IMaterialControl_**

**Comment by lifehome** [comment]
Is it possible to use this patch/PR through NuGet, without the hassle of @IgnaceMaes accepting it?

**Comment by IgnaceMaes** [comment]
I merged the PR.
Thank you for the contribution, a code cleanup was welcome!

Sorry for the late response, I'm not actively maintaining this repository anymore.

**Comment by marcelo2108** [comment]
Thank u!

**Pull request merged**
